"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$status\
$cmd_duration\
$line_break\
$python\
$character"""

[package]
disabled = true

[username]
show_always = true
format = '[$user]($style)'

[hostname]
ssh_only = false
format = '@[$ssh_symbol$hostname]($style) '

[directory]
truncate_to_repo = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[status]
# style = 'bg:red'
format = '[\[$status $symbol$common_meaning$signal_name\]]($style) '
map_symbol = true
disabled = false

[cmd_duration]
show_milliseconds = true
show_notifications = false
